### ISSUE TITLE
Are the v2 files scripts needed?

### ISSUE THREAD

**Issue by eliandoran** [edc22osm/viofo2jpg#2]
Both `dashcam2josm` and `nvtk_mp42gpx` have a `_v2` and `_v3` script. Initially I thought they were for Python 2, respectively 3 but it appears they are actually two different versions of the same script, with v2 being quite a bit older.

Considering these versions are quite old, I think a slightly better approach would be to remove them from the repository. If they are still needed, maybe they can be moved to a `v2` branch. This will remove any potential confusions.

**Comment by edc22osm** [comment]
My *_v2 scripts was developed from earlier versions of scripts from https://sergei.nz/  *_v3 scripts was developed after.
Yes, it's better to make one version to remove confusions.
I removed old *_v2 scripts and rename *_v3 scripts to the only ones.
Thanks for Your contributions.
